import Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  APP_NAME: Joi.string().default('nestjs-scaffold'),
  APP_PORT: Joi.number().port().default(3000),
  HTTP_ADAPTER: Joi.string().valid('express', 'fastify').default('express'),
  GLOBAL_PREFIX: Joi.string().allow('').default('api'),
  CORS_ORIGINS: Joi.string().allow('').default('*'),
  DB_TYPE: Joi.string().valid('postgres', 'mysql').default('postgres'),
  DATABASE_URL: Joi.string().optional(),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().port().required(),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().allow('').required(),
  DB_DATABASE: Joi.string().required(),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRES_IN: Joi.string().default('1h'),
  REFRESH_TOKEN_EXPIRES_IN_DAYS: Joi.number().integer().positive().default(30),
  BCRYPT_ROUNDS: Joi.number().integer().min(8).max(15).default(12),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().port().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_DB: Joi.number().integer().min(0).default(0),
  RABBITMQ_URL: Joi.string().uri().required(),
  RABBITMQ_EXCHANGE: Joi.string().allow('').default('app.events'),
  RABBITMQ_EXCHANGE_TYPE: Joi.string()
    .valid('direct', 'topic', 'fanout', 'headers')
    .default('topic'),
  RABBITMQ_BINDING_KEY: Joi.string().allow('').default('#'),
  RABBITMQ_MAX_RETRIES: Joi.number().integer().min(1).max(2).default(2),
  RABBITMQ_QUEUE: Joi.string().required(),
  RABBITMQ_CONSUMER_ENABLED: Joi.boolean().default(true),
  RABBITMQ_DLQ_CONSUMER_ENABLED: Joi.boolean().default(true),
  RABBITMQ_PREFETCH: Joi.number().integer().positive().default(10),
  RABBITMQ_DLQ_THRESHOLD: Joi.number().integer().min(0).default(0),
  SWAGGER_ENABLED: Joi.boolean().default(true),
  SWAGGER_PATH: Joi.string().default('docs'),
  OPENAPI_EXPORT: Joi.boolean().default(false),
  RATE_LIMIT_TTL: Joi.number().integer().positive().default(60000),
  RATE_LIMIT_LIMIT: Joi.number().integer().positive().default(120),
  TENANT_HEADER: Joi.string().default('x-tenant-id'),
  TENANT_RESOLUTION: Joi.string().valid('header', 'subdomain').default('header'),
  SEED_ADMIN_ENABLED: Joi.boolean().default(false),
  SEED_ADMIN_EMAIL: Joi.string().email().optional(),
  SEED_ADMIN_PASSWORD: Joi.string().min(8).optional(),
  VERIFY_CODE_TTL_SECONDS: Joi.number().integer().min(60).default(300),
  VERIFY_CODE_COOLDOWN_SECONDS: Joi.number().integer().min(1).default(60),
  VERIFY_CODE_FIXED: Joi.string().length(6).optional(),
  VERIFY_CODE_PROVIDER: Joi.string().valid('log', 'webhook', 'aliyun').optional(),
  VERIFY_CODE_DELIVERY_WEBHOOK_URL: Joi.string().uri().optional(),
  ALIBABA_CLOUD_ACCESS_KEY_ID: Joi.string().optional(),
  ALIBABA_CLOUD_ACCESS_KEY_SECRET: Joi.string().optional(),
  ALIYUN_SMS_SIGN_NAME: Joi.string().optional(),
  ALIYUN_SMS_TEMPLATE_CODE: Joi.string().optional(),
  ALIYUN_MAIL_FROM_ADDRESS: Joi.string().email().optional(),
  ALIYUN_MAIL_FROM_NAME: Joi.string().optional(),
  OUTBOX_RETENTION_HOURS: Joi.number().integer().min(1).default(72),
});
