import Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  APP_NAME: Joi.string().default('nestjs-production-scaffold'),
  APP_PORT: Joi.number().port().default(3000),
  HTTP_ADAPTER: Joi.string().valid('express', 'fastify').default('express'),
  GLOBAL_PREFIX: Joi.string().allow('').default('api'),
  CORS_ORIGINS: Joi.string().allow('').default('*'),
  DB_TYPE: Joi.string().valid('postgres', 'mysql').default('postgres'),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().port().required(),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().allow('').required(),
  DB_DATABASE: Joi.string().required(),
  DB_SYNCHRONIZE: Joi.boolean().default(false),
  DB_LOGGING: Joi.boolean().default(false),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRES_IN: Joi.string().default('1h'),
  REFRESH_TOKEN_EXPIRES_IN_DAYS: Joi.number().integer().positive().default(30),
  BCRYPT_ROUNDS: Joi.number().integer().min(8).max(15).default(12),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().port().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_DB: Joi.number().integer().min(0).default(0),
  RABBITMQ_URL: Joi.string().uri().required(),
  RABBITMQ_QUEUE: Joi.string().required(),
  RABBITMQ_CONSUMER_ENABLED: Joi.boolean().default(true),
  RABBITMQ_PREFETCH: Joi.number().integer().positive().default(10),
  SWAGGER_ENABLED: Joi.boolean().default(true),
  SWAGGER_PATH: Joi.string().default('docs'),
  RATE_LIMIT_TTL: Joi.number().integer().positive().default(60000),
  RATE_LIMIT_LIMIT: Joi.number().integer().positive().default(120),
  TENANT_HEADER: Joi.string().default('x-tenant-id'),
  SEED_ADMIN_ENABLED: Joi.boolean().default(false),
  SEED_ADMIN_EMAIL: Joi.string().email().optional(),
  SEED_ADMIN_PASSWORD: Joi.string().min(8).optional(),
});
